### ISSUE TITLE
Port to .NET Core / .NET Standard

### ISSUE THREAD

**Issue by unclearParadigm** [holzmaster/OpenPr0gramm#17]
Hi,

Große Teile der Codebasis wären ohne gröbere Probleme auf .NET Core bzw. .NET Standard portierbar und wären dadurch auch einfacher von anderen Platformen benutzbar (Blick in Richtung Linux/UNIX). Auch alle verwendeten Dependencies (Refit, Newtonsoft.Json, ...) haben bereits .NET Standard Ports am Start. 

Ich könnte das gerne übernehmen, wenn es denn auch von deiner Seite erwünscht ist.

Cheers,

**Comment by holzmaster** [comment]
Hi!

Ich wollte die Library sowieso mal wieder anfassen, da kann ich das gleich auch machen. Hab nicht mitbekommen, dass Refit nun auch .NET Standard kann. Dann werde ich das am WE mal portieren.

Edit:
Sehe gerade, dass das offenbar schon passiert ist?
https://github.com/holzmaster/OpenPr0gramm/pull/14

Kann sein, dass das noch nicht gepublished ist. Es sind aber auf jeden Fall noch alte Configs im Projekt, die man mal löschen/aufräumen könnte. CI gibts momentan glaub ich auch nur via AppVeyor. Da könnte man noch ein CD dranhängen.

**Comment by unclearParadigm** [comment]
Asche über mein Haupt! Hab ich völlig übersehen.
Danke.

**Comment by holzmaster** [comment]
Habe mal etwas aufgeräumt. Leider kann ich auf NuGet nichts mehr veröffentlichen, da man sich jetzt nur noch mit einem MS-Account einloggen kann. Dafür muss ich noch ne Lösung finden.

Hab in dem Zug auch mal CI/CD und die Tests gefixt.
