### ISSUE TITLE
consider releasing latest build

### ISSUE THREAD

**Issue by peanutbother** [holzmaster/OpenPr0gramm#5]
please release latest build of master as new relese, so we can use it in nuget for uwp projects.

**Comment by holzmaster** [comment]
It's on my list.

**Comment by peanutbother** [comment]
thanks!

**Comment by holzmaster** [comment]
I just implemented proper CI and CD. However, I cannot publish the package to Nuget automatically because the login using NuGet credentials is deprecated. I don't want to use a microsoft account. We have to get a solution for that.

**Comment by holzmaster** [comment]
We may just create a dummy MS account for that. Or maybe we can soon log in via GitHub?

**Comment by peanutbother** [comment]
I would just create a dummy account for that as long as the issue with microsoft continues to exist.
Then we could reopen the issue once microsoft opens the gates for other ways to release.

**Comment by unclearParadigm** [comment]
any updates on this?

**Comment by holzmaster** [comment]
I can do it tomorrow.
Also, it does not seem possible to log in with a NuGet account any more. So it may not be possible to keep the package name, since we cannot migrate the account.

**Comment by holzmaster** [comment]
I just published the latest AppVeyor build. It's on `v1.0.0`. I hope we can manage to set up some CD for the package.
